[server]
# headless = true
runOnSave = true
allowRunOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[theme]
base='light'
primaryColor="#aa0000"
backgroundColor="#E6EAF1"
#backgroundColor="#BDC4C7"
secondaryBackgroundColor="#8c9cb8"
textColor="#000000"

[secrets]
