[color_options]
greenishgrey="#96A78B"
lichen="#93B67C"
celery="#BBF495"
nastygreen='#8DD35F'
leafgreen='#63B020'
darkishgreen="#2C7D32"
dark="#2A3B4A"
charcoalgrey="#3A484F"
gunmetal="#5B676C"
indianred="#800000"
2dark="#26313A"
white="#FFFFFF"
black="#000000"
silver="#BDC4C7"
evergreen="#2B5C3E"
coolgrey="#96A2A6"
palegrey="#E6EAF1"
battleshipgrey="#69777D"